#!/usr/bin/env python3
"""Extract chatgpt.com / openai.com session cookies from Chrome/Edge.

Writes:
  re/captures/cookies.netscape   (for curl)
  re/captures/cookies.json       (names + domains + expiry; values redacted by default)
  re/captures/cookies.full.json  (full values; gitignored — local only)

Usage:
  python scripts/extract_cookies.py
  python scripts/extract_cookies.py --browser edge
  python scripts/extract_cookies.py --show-values   # include secrets in stdout summary
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import browser_cookie3
except ImportError:
    print("pip install browser-cookie3", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parents[1]
CAP = ROOT / "re" / "captures"
DOMAINS = ("chatgpt.com", "openai.com", "chat.openai.com", "auth0.openai.com")
INTERESTING = (
    "__Secure-next-auth.session-token",
    "__Secure-next-auth.session-token.0",
    "__Secure-next-auth.session-token.1",
    "oai-did",
    "oai-sc",
    "oai-client-auth-file",
    "_account",
    "__cf_bm",
    "cf_clearance",
    "__cflb",
    "oai-nav-state",
    "_puid",
    "oai-hm",
)


def load_jar(browser: str):
    loaders = {
        "chrome": browser_cookie3.chrome,
        "edge": browser_cookie3.edge,
        "chromium": browser_cookie3.chromium,
    }
    fn = loaders.get(browser)
    if not fn:
        raise SystemExit(f"unknown browser: {browser}")
    # domain_name filter is substring match in browser_cookie3
    jars = []
    for d in ("chatgpt.com", "openai.com"):
        try:
            jars.append(fn(domain_name=d))
        except Exception as e:
            print(f"warn: {browser} {d}: {e}", file=sys.stderr)
    return jars


def cookie_rows(jars):
    seen = set()
    rows = []
    for jar in jars:
        for c in jar:
            key = (c.domain, c.name, c.path)
            if key in seen:
                continue
            seen.add(key)
            if not any(d in (c.domain or "") for d in DOMAINS):
                continue
            rows.append(
                {
                    "domain": c.domain,
                    "name": c.name,
                    "value": c.value,
                    "path": c.path or "/",
                    "secure": bool(c.secure),
                    "expires": c.expires,
                    "interesting": c.name in INTERESTING
                    or "session" in (c.name or "").lower()
                    or c.name.startswith("__Secure-next-auth")
                    or c.name.startswith("oai-"),
                }
            )
    rows.sort(key=lambda r: (not r["interesting"], r["domain"], r["name"]))
    return rows


def write_netscape(rows: list[dict], path: Path) -> None:
    lines = ["# Netscape HTTP Cookie File", "# generated by extract_cookies.py"]
    for r in rows:
        # domain_specified flag: leading dot in domain
        domain = r["domain"]
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if r["secure"] else "FALSE"
        exp = int(r["expires"] or 0)
        lines.append(
            f"{domain}\t{include_sub}\t{r['path']}\t{secure}\t{exp}\t{r['name']}\t{r['value']}"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--browser", default="chrome", choices=["chrome", "edge", "chromium"])
    ap.add_argument("--show-values", action="store_true")
    args = ap.parse_args()

    CAP.mkdir(parents=True, exist_ok=True)
    jars = load_jar(args.browser)
    rows = cookie_rows(jars)
    if not rows:
        print(
            f"No cookies for chatgpt/openai from {args.browser}.\n"
            "Log into https://chatgpt.com in that browser, then re-run.\n"
            "If Chrome is open and this fails, fully quit Chrome and retry.",
            file=sys.stderr,
        )
        return 2

    full_path = CAP / "cookies.full.json"
    redacted_path = CAP / "cookies.json"
    netscape_path = CAP / "cookies.netscape"
    meta = {
        "browser": args.browser,
        "extracted_at": datetime.now(timezone.utc).isoformat(),
        "count": len(rows),
        "interesting_count": sum(1 for r in rows if r["interesting"]),
    }

    full_path.write_text(
        json.dumps({"meta": meta, "cookies": rows}, indent=2), encoding="utf-8"
    )
    redacted = []
    for r in rows:
        rr = dict(r)
        v = rr.pop("value")
        rr["value_len"] = len(v or "")
        rr["value_preview"] = (v[:6] + "…") if v and len(v) > 6 else ("***" if v else "")
        redacted.append(rr)
    redacted_path.write_text(
        json.dumps({"meta": meta, "cookies": redacted}, indent=2), encoding="utf-8"
    )
    write_netscape(rows, netscape_path)

    print(f"browser={args.browser} cookies={len(rows)} interesting={meta['interesting_count']}")
    print(f"wrote {redacted_path}")
    print(f"wrote {full_path}  (SECRETS — do not commit)")
    print(f"wrote {netscape_path}")
    print("--- interesting ---")
    for r in rows:
        if not r["interesting"]:
            continue
        if args.show_values:
            print(f"  {r['domain']}\t{r['name']}\tlen={len(r['value'] or '')}\t{r['value'][:40]}…")
        else:
            print(f"  {r['domain']}\t{r['name']}\tlen={len(r['value'] or '')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
